server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/daycountersdb?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: postgres
    password: qwerty
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create
  properties:
    hibernate:
      format_sql: true
logging:
  level:
    root: INFO